### ISSUE TITLE
Alf Shatterer issues

### ISSUE THREAD

**Issue by Nagispace** [noeppi-noeppi/MythicBotany#10]
# List of issues
- ~~Alf shatterer can't mine block if player is equipped with mana generating equipment(due to the NBT constantly changing)~~(should be fixed in latest)
- Allf shatterer mine a 9*9*1 area when active just like the Terra Shatterer (unlike the book suggest) (edit: only happens when mining vertically) 
![image](https://user-images.githubusercontent.com/65559593/98907617-5f3b3000-24bf-11eb-9550-a9c2e07739ae.png)
- Alf shatterer combined with an elementium pickaxe will still mine and drop cobblestone, stone, etc...

# Game infos
Modpack ATM6 with some edits
Mythic Botany : `MythicBotany-1.16.3-1.1.6`

**Comment by noeppi-noeppi** [comment]
This is intended to prevent fall damage when mining down. I will make it clearer in the lexica botania

**Comment by noeppi-noeppi** [comment]
I'll take a look to the problem with the tipped variant.
