### ISSUE TITLE
Mjollnir ritual completely missing from my book with all advancements.

### ISSUE THREAD

**Issue by jakesnek** [noeppi-noeppi/MythicBotany#102]
Title really says it all. I'll add a screenshot for reference. Tried using someone elses recipe online too but for some reason it told me the ingredients were wrong when it had worked for them.
![image](https://user-images.githubusercontent.com/53923383/164122721-1d8bc0bb-f162-403f-a101-6eb279634ac3.png)

**Comment by jakesnek** [comment]
![image](https://user-images.githubusercontent.com/53923383/164131604-aa742010-b560-460b-ba2f-792e420bea36.png)

Here's a screenshot of the mythic botany chapter.

**Comment by noeppi-noeppi** [comment]
Fixed in next version
