### ISSUE TITLE
Spark Compatible Runic altar

### ISSUE THREAD

**Issue by tyler489** [noeppi-noeppi/MythicBotany#104]
I would love to see the Runic altar made compatible with sparks or an upgraded version of the runic altar, especially since MythicBotany adds the mana collector, which basically removes the need for spreaders entirely.

**Comment by noeppi-noeppi** [comment]
This won't come in MythicBotany. However, [botanical machinery](https://www.curseforge.com/minecraft/mc-mods/botanical-machinery) has that feature.
