### ISSUE TITLE
Portal doesn't give time to get out. 

### ISSUE THREAD

**Issue by OceanHobo** [noeppi-noeppi/MythicBotany#107]
I can't go back to the overworld the portal teleports me right back before I can get out of it there is no over time warbling like the nether portal

**Comment by noeppi-noeppi** [comment]
What does *teleports me right back* mean? There should be a 4 second delay before porting the player back. However I just increased it to 8 seconds to give a little more time.

**Comment by OceanHobo** [comment]
So say I started in alfeim (where my hosue is) and wanted to go back to the overworld. I would step in the portal and get a load screen and then id be in the overwold for about half a second before getting another load screen and be back in alfheim before I could get outa the portal. I'm assuming there was some lag between me and the server so that by the time it had loaded my screen on my end the server saw me as standing there for 4 seconds.

**Comment by OceanHobo** [comment]
its not doing it anymore tho so all seems well.
