### ISSUE TITLE
Biomes not generating

### ISSUE THREAD

**Issue by Thor123xyz** [noeppi-noeppi/MythicBotany#115]
Mythic Botany biomes won't generate, unsure of the mod that caused the conflict.

Version: 1.8.2

The mods used are: 
![first](https://user-images.githubusercontent.com/109337682/179171937-7fd364d9-c24b-493b-a834-e4f897c3c3ae.jpeg)
![second](https://user-images.githubusercontent.com/109337682/179171951-667d6580-7836-431e-b85e-294c67940d45.jpeg)

The biomes won't spawn in the server, or my own private worlds. Have used the locate command so many times and couldn't find a single biome in the overworld.

**Comment by noeppi-noeppi** [comment]
MythicBotany does not add any biomes to the overworld. The biomes added by MythicBotany all generate in the Alfheim dimension.

**Comment by Thor123xyz** [comment]
I thought you can't get to alfheim and the portal only transfers items, how do I go to alfheim?

**Comment by noeppi-noeppi** [comment]
You need to drink from the mead of kvasir. After that, you can go through the portal.
