### ISSUE TITLE
Greatest Band of Aura not producing mana.

### ISSUE THREAD

**Issue by kjchiamu** [noeppi-noeppi/MythicBotany#12]
With a tainted blood pendant on, a mana tablet in my inventory, and the Greatest Band of Aura equipped, I don't get the Regen 2 buff. Tested it works with the Greater Band of Aura.

Likely caused by the IManaGivingItem class being deprecated from Botania.

**Comment by noeppi-noeppi** [comment]
Not reproducible. Do you use the latest version? And are there any other mods installed?

**Comment by kjchiamu** [comment]
Running All The Mods 6. It looks to be working now. I don't think I was running on the latest version at the time. Thanks.
