### ISSUE TITLE
Crash on startup, IllegalAccessError between MythicBotany and Botania 

### ISSUE THREAD

**Issue by DaanMansour** [noeppi-noeppi/MythicBotany#124]
Forge: 40.1.85
MythicBotany: 1.18.2-2.1.14
Botania: 1.18.2-435
Does as the title says, causes a crash on startup, attached is the crashlog.
[crash-2022-11-26_04.12.54-client.txt](https://github.com/noeppi-noeppi/MythicBotany/files/10096949/crash-2022-11-26_04.12.54-client.txt)

**Comment by noeppi-noeppi** [comment]
This is a problem with ExtraBotany, not MythicBotany.

**Comment by DaanMansour** [comment]
sorry, i misread. My apologies
