### ISSUE TITLE
[1.16.5] Faded nether stars despawning 

### ISSUE THREAD

**Issue by Fredthegeek** [noeppi-noeppi/MythicBotany#125]
I do not know if this is a bug or an intended feature but I am playing ATM6 and my Faded nether stars are despawning after 5 after only about 5% of durability is gone and it makes the creation of alfsteel impossible without mana pools as the nether star despawns before creation is complete. Is there anyway to fix this or change it or is it an intended feature that cannot be changed

**Comment by zValente** [comment]
The same problem with me, however if you use a mana collector everything works great.
