### ISSUE TITLE
Ring of Andwari always gets cursed

### ISSUE THREAD

**Issue by Sky-Evil** [noeppi-noeppi/MythicBotany#129]
This ring never consumes mana, and always becomes cursed after 32 gold blocks are set.

MythicBotany-1.18.2-2.1.14.jar

**Comment by noeppi-noeppi** [comment]
That is the intended behaviour. You repeatedly have to remove the curse. You can also remove the curse from a damaged ring and reset the damage.

It should consume mana though.

**Comment by noeppi-noeppi** [comment]
Works as intended
