### ISSUE TITLE
1.20 crash

### ISSUE THREAD

**Issue by oof100200** [noeppi-noeppi/MythicBotany#137]
[crash-2024-02-02_19.42.08-client.txt](https://github.com/noeppi-noeppi/MythicBotany/files/14139487/crash-2024-02-02_19.42.08-client.txt)

**Comment by noeppi-noeppi** [comment]
I don't see any indications in the crash log that this issue is related to MythicBotany in any way.
Therefore I am going to close this issue now. If you are certain, this is related to MythicBotany, feel free to provide more information and I'll reopen the issue.
