### ISSUE TITLE
In 1.20.1, cannot load a map created in 1.19.2

### ISSUE THREAD

**Issue by rikigeek** [noeppi-noeppi/MythicBotany#139]
Hi, when trying to load a world save created in 1.19.2, I first get a message "Errors in currently selected data packs prevented the world from loading". When trying the safe mode, it fails, telling me the world contains invalid or corrupted data.

# Step to reproduce 
Start MC 1.19.2, forge 43.2.3, with the following mods:
  [✔️] Botania-1.19.2-440-FORGE.jar
  [✔️] curios-forge-1.19.2-5.1.4.1.jar
  [✔️] LibX-1.19.2-4.2.8.jar
  [✔️] MythicBotany-1.19.2-3.0.2.jar
  [✔️] Patchouli-1.19.2-77.jar
  [✔️] SandBox-1.19.2-1.0.1.jar
Java is version 17.0.9, using 64-bit architecture
Create a new world, save and quit

Start MC 1.20.1, with forge version 47.2.0, Java is version 17.0.9, with the following mods:
  [✔️] Botania-1.20.1-443-FORGE.jar
  [✔️] curios-forge-5.7.0+1.20.1.jar
  [✔️] LibX-1.20.1-5.0.12.jar
  [✔️] MythicBotany-1.20.1-4.0.2.jar
  [✔️] Patchouli-1.20.1-84-FORGE.jar
Copy the world created in 1.19.2 and open it.

# Error messages
Render thread/WARN] [minecraft/MinecraftServer]: Missing data pack mod:sandbox
[...]
[Render thread/ERROR] [minecraft/LevelStorageSource]: WorldGenSettings: Unknown registry key in ResourceKey[minecraft:root / minecraft:worldgen/chunk_generator]: sandbox:noise missed input: {"mythicbotany:alfheim":{generator:{biome_source:{horizontal_scale:48.0d,layers:"mythicbotany:alfheim",type:"sandbox:layered",vertical_scale:120.0d},settings:"mythicbotany:alfheim",surface_override:"mythicbotany:alfheim_surface",type:"sandbox:noise"},type:"mythicbotany:alfheim"}}
[Render thread/WARN] [minecraft/WorldOpenFlows]: Failed to load level data or datapacks, can't proceed with server load

## Log files
[latest.log](https://github.com/noeppi-noeppi/MythicBotany/files/14202406/latest.log)

Let me know what I can do to help you with this issue. Thanks!

**Comment by rikigeek** [comment]
Oh... bad news. Do you know if there is a way to "manually" edit my world save to remove those "registry key"? Or any clue you can give me?
I play on a map for one year now with my son, and we definitely don't want to start from scratch :(

**Comment by noeppi-noeppi** [comment]
You could edit the `level.dat` file and remove the `Data` -> `WorldGenSettings` -> `dimensions` -> `mythicbotany:alfheim` part. This may however break your alfheim worldgen at the chunk borders of what has been generated in 1.19. (Or maybe just make them look weird because of blending, I am not sure.)
Also make a backup before you edit `level.dat`.

**Comment by rikigeek** [comment]
Ok, I will have a look on this. Thanks for your feedback. And thanks for your mod, this one is awesome!
