### ISSUE TITLE
[1.19.2] Alfheim - I'm getting blindness put on me always.

### ISSUE THREAD

**Issue by vgrynch** [noeppi-noeppi/MythicBotany#140]
Any clues on what mod can cause it or how to get rid of it?
![image](https://github.com/noeppi-noeppi/MythicBotany/assets/46818018/bee0d93e-6625-4d0f-b42c-a04d6d174c73)

**Comment by vgrynch** [comment]
Note: When drinking milk, I see everything rendered normally, just for a moment. Then blindness re-applies immediately.

**Comment by noeppi-noeppi** [comment]
This happens, when you access the Alfheim dimension without properly playing through MythicBotany. (You haven't drunk from the mead of kvasir and therefore, you aren't able to experience Alfheim.)
Anyway: There is a config option (`alfheim_locked`) to disable this behaviour.

**Comment by vgrynch** [comment]
Thanks!
Would be good to inform about it somewhere on the mod description. Unaware admins checking if mod works may consider it is malfunctioning, like me did, LoL.
