### ISSUE TITLE
Automation of Rune Ritual（Suggestion）

### ISSUE THREAD

**Issue by Y-Xiao233** [noeppi-noeppi/MythicBotany#143]
Hello Noeppi,Mythic botany is a great extension of botania, as it offers several new synthesis methods that are very interesting.

As the author of the modpack, the central rune holder in the rune ritual of Mythic botany cannot be automatically clicked to achieve fully automated synthesis. Can you add a dummy that can input mana and right-click to automatically synthesize, in order to meet the automation requirements of the modpack.

I will be glad to receive your reply, regardless of whether you are willing to add this feature to it or not

**Comment by noeppi-noeppi** [comment]
Rune ritual automation is possible using the *Petrunia* functional flower.
