### ISSUE TITLE
World crash

### ISSUE THREAD

**Issue by GnomTocha** [noeppi-noeppi/MythicBotany#16]
The world will crash when a mob appears in armor from this mod. Sorry for my English.
[crash-2020-12-09_16.43.27-client.txt](https://github.com/noeppi-noeppi/MythicBotany/files/5666653/crash-2020-12-09_16.43.27-client.txt)

**Comment by noeppi-noeppi** [comment]
![zombie_alfsteel](https://user-images.githubusercontent.com/63002502/101656099-9f4fed00-3a42-11eb-83b7-5ed92617a7c0.png)

Not reproducible. Could you try it without any other mods installed?

**Comment by GnomTocha** [comment]
In the configs of the improvedmobs mod, I increased Equipment Chance "=
0.6. The world crashes when skeletons appear, or mini skeletons with the
MekanismAdditions mod. I did not check it on other mobs. I do not exclude a
mod conflict. I will exclude mods one by one and look for the
reason.Configs only once were mentioned to me by dungeons gear and
ImmersiveEngineering as the reason, but their exclusion did not help.

ср, 9 дек. 2020 г. в 19:19, noeppi_noeppi <notifications@github.com>:

**Comment by GnomTocha** [comment]
![image](https://user-images.githubusercontent.com/75666317/101660562-5efb6980-3a58-11eb-976f-171db01e0046.png)
[crash-2020-12-09_18.51.47-client.txt](https://github.com/noeppi-noeppi/MythicBotany/files/5667429/crash-2020-12-09_18.51.47-client.txt)
I removed all other mods from the pack.

**Comment by GnomTocha** [comment]
[https://youtu.be/rUJb_vG5EMk](url)

**Comment by GnomTocha** [comment]
https://youtu.be/rUJb_vG5EMk

**Comment by noeppi-noeppi** [comment]
Are you using the latest version? And can you try without optifine?

**Comment by GnomTocha** [comment]
I am using the latest version of all mods and have tried it without optfine.

ср, 9 дек. 2020 г., 21:13 noeppi_noeppi <notifications@github.com>:

**Comment by GnomTocha** [comment]
My logs https://pastebin.com/JuBHgvFL

ср, 9 дек. 2020 г., 21:45 Anton Bidenko <anton.bidenko3@gmail.com>:

**Comment by noeppi-noeppi** [comment]
Seems like botania changed something there that makes my mod crash. Ill get a fix out soon.

**Comment by GnomTocha** [comment]
OK.  thanks

ср, 9 дек. 2020 г., 22:09 noeppi_noeppi <notifications@github.com>:
