### ISSUE TITLE
Alf Shatterer Breaking bedrock when ring of Thor is equipped.

### ISSUE THREAD

**Issue by Mikaaah** [noeppi-noeppi/MythicBotany#17]
As the Title says, Ive been using the mod for a bit, but every since I obtained the ring of Thor, the alf shatterer seems to be able to break bedrock if you mine the block above it

**Comment by noeppi-noeppi** [comment]
I just tested it without mythic botany installed and with a terra shatterer and it works there too. So maybe you should report an issue at botania?

**Comment by noeppi-noeppi** [comment]
Related: https://github.com/Vazkii/Botania/issues/3583
