### ISSUE TITLE
Critical hit crashes game

### ISSUE THREAD

**Issue by Xanthiosaurus** [noeppi-noeppi/MythicBotany#21]
Whenever I jump attack a mob, the game immediately crashes. Crash log says

java.lang.NoSuchMethodError: mythicbotany.alftools.AlfsteelHelm.onCritDamageCalc(FLnet/minecraft/entity/player/PlayerEntity;)F

This happens despite nothing related to the mod loaded (no armor, tools, anything on self or mobs)

[crash-2021-02-04_00.10.14-server.txt](https://github.com/noeppi-noeppi/MythicBotany/files/5923685/crash-2021-02-04_00.10.14-server.txt)
[crash-2021-02-04_00.10.19-client.txt](https://github.com/noeppi-noeppi/MythicBotany/files/5923686/crash-2021-02-04_00.10.19-client.txt)

**Comment by noeppi-noeppi** [comment]
Which version of botania are you using? If you're anything below 1.16.4-411, please test it with said version and let me know if that fixes the issue.

**Comment by Xanthiosaurus** [comment]
I was using 1.16.4-410; updating seems to have fixed it. Thank you!
