### ISSUE TITLE
Raindeltia not generating during normal rain, only thunder storms

### ISSUE THREAD

**Issue by TheInfamousAlk** [noeppi-noeppi/MythicBotany#23]
I am using the latest version of all the mods 6 (1.5.2), and botania version 1.16.4-411, and mythicbotany version 1.6.3-1.2.4. 

In the last update from all the mods 1.5.1 to 1.5.2, the raindeltias stopped working during normal rain and now only work during thunder storms.

![image](https://user-images.githubusercontent.com/29339124/107648345-2fc8ca80-6c4a-11eb-97d8-a12c3ae1cb24.png)

**Comment by noeppi-noeppi** [comment]
It is intended that the raindeletia only produces mana during a thunderstorm if not placed on vivid grass or enchanted soil. In the current version it also won't generate mana on vivid grass, I am going upload a fix to curseforge very soon.

**Comment by TheInfamousAlk** [comment]
Oh cool. The mythic botany section of the guidebook still says it generates in rain and even more in thunderstorms, which is why I was confused.
