### ISSUE TITLE
Mana-Infuser doesn't pull from spark the same way as Terrestrial Agglomeration Plate?

### ISSUE THREAD

**Issue by heloman1** [noeppi-noeppi/MythicBotany#24]
Version: 1.2.4

If I try to make either Terrasteel or Alfsteel using the Mana-Infuser, it seems to only pull from sparks that have the recessive augment, whereas the Agglomeration Plate will pull from all sparks. Is this intentional?

**Comment by TheInfamousAlk** [comment]
You need to put the dominant spark augment on the plate. I think it also says this in the guidebook, so it's intentional I think.

**Comment by heloman1** [comment]
Ah, my bad. It does indeed say that in the book.

Although, it might make sense to highlight it (like the Agglo Plate already is on that page) so it is more visible to people like me who just skim through the book without fully reading it.

(I'll leave this open if noeppi wants to mark it as an enhancement or close it)
