### ISSUE TITLE
Shatterer Loses Enchants when Placed in Pool

### ISSUE THREAD

**Issue by desagas** [noeppi-noeppi/MythicBotany#25]
I am not sure if it is instant or not, but, every time I have thrown my Alf Shatterer into a mana pool, whether it levels up or not, ALL the enchants are wiped off of the tool.

Playing ATM6-1.5.2, on Forge 36.0.21, with MB MythicBotany-1.16.3-1.2.4

**Comment by noeppi-noeppi** [comment]
If have left a shatterer for 10 minutes now in a pool and nothing happens. So how long have you left it there and have you tried it with only MythicBotany and it's dependencies?

**Comment by desagas** [comment]
I apologize, this is totally a blond moment for me ... I have a rosa arcana set up right above my pools, and I didn't even think that the shatterer was close enough to be stripped of its enchantments. Bahahah. Ill just close this right here. Great mod.
