### ISSUE TITLE
Some suggestions

### ISSUE THREAD

**Issue by Unhook** [noeppi-noeppi/MythicBotany#3]
An idea for a new flower:
- rain flower: generates mana while it is raining

It would also be nice to see a new mana pool that is 2x the size of a normal mana pool.

**Comment by noeppi-noeppi** [comment]
The flower is a cool idea. I don't think I am going to create a bigger mana pool but [Botanical Machinery](https://www.curseforge.com/minecraft/mc-mods/botanical-machinery) has a mana battery that can store 10 times as much as a mana pool.
