### ISSUE TITLE
1.2.10: Startup Crash @[java.lang.VerifyError: class mythicbotany.data.BlockTagProvider overrides final method]

### ISSUE THREAD

**Issue by sciguyryan** [noeppi-noeppi/MythicBotany#31]
Hi.

After upgrading to 1.2.10 I get the following crash at startup:

```java.lang.VerifyError: class mythicbotany.data.BlockTagProvider overrides final method io.github.noeppi_noeppi.libx.data.provider.BlockTagProviderBase.func_200432_c()V```

The full crash report can be found here: https://pastebin.com/pSZiay8g

I have not changed anything else. If there is any further information you need to help track this down, please do let me know.

Cheers.

**Comment by noeppi-noeppi** [comment]
1. You should not use LibX alpha builds to play the game.
2. Will be fixed soon. For now just downgrade LibX to the latest release version.

**Comment by sciguyryan** [comment]
> You should not use LibX alpha builds to play the game. 

I do so mainly for testing purposes as it often helps to pick up bugs. I do not use them in my master pack, just in the testing branch.
