### ISSUE TITLE
Hope to add Chinese translation

### ISSUE THREAD

**Issue by DevilJueChen** [noeppi-noeppi/MythicBotany#33]
As I said in Curseforge, I will reproduce your mod to MCBBS with the direct download link to your page. However, it will be better if you can add Chinese localization. I have done the translation but could you kindly add the language file into your mod since I have no way to clone your project in China. Thanks a lot! (Language file attached below)
[zh_cn.zip](https://github.com/noeppi-noeppi/MythicBotany/files/6311771/zh_cn.zip)

**Comment by noeppi-noeppi** [comment]
1. If you translate the lexica please make sure formatting codes are correct. Example: `$(l：botania：baubles / mana_ring)` Here the colon is not the right character which will not display correctly. should use a normal colon instead, (`:`). Also the spaces before and after the slash will cause it to display wrong. So please make sure to fix this.
2. I don't think the `『』` characters around the flower descriptions are chinese. (At least google translate does not translate these). So could you remove them please just to keep things consistent between language files.
3. I'm not sure about the flower names. Might be that google translate translated them wrongly but they're all puns (like botania does as well). I have listed the real flower names here so you can just translate these if there's no good pun. Might also be that google translate was a little bit weird about these and they're translated good.
  * *Aquapathus* comes from *Agapanthus*
  * Exoblaze should be fine
  * Hellebore is a real flower name but it was still translated weird by google translate
  * *Raindeletia* comes from *Rondeletia*
  * *Wither Aconite* comes from *Winter Aconite*

**Comment by wisdommen** [comment]
Hi noeppi:
I am the one who is helping him creating a pull request. He agrees with you about point 1, 2 and he will fix it in the next version, but he suggests that raindeletia and wither_aconite will sound more localized if you accept his translation. Btw, he will fix the translation of Aquapathus.

Cheers

**Comment by DevilJueChen** [comment]
Please tell me why it is closed

**Comment by noeppi-noeppi** [comment]
The pull request was merged

**Comment by noeppi-noeppi** [comment]
I'll upload it to curseforge soon

**Comment by DevilJueChen** [comment]
OK，bother you

**Comment by TUsama** [comment]
Hi, @noeppi-noeppi I'd like to ask you some questions about the CHS translation.

1. The _Aquapathus_ comes from the _Agapanthus_, In CHS, the translation of "Agapanthus" is "百子莲"(weird, the "百” means "hundred", the "子" means "child"), could I just change a word, translate it to "百水莲"？ The middle word "水“ means "water" as well as "aqua".This is not a strict pun, but I think this could express this word trick partially.
2. The _Exoblaze_ means "Exo-"+" blaze"? If so, "火焰花” only means "blaze flower", so maybe this is not a good translation.
3. _Raindeletia_ comes from _Rondeletia_, for the "Rondeletia" in CHS, the translation is "郎德木", totally Transliteration word, "郎德"'s pronunciation is similar to "Ronde". In this case, could this flower be translated to "雨德木"? "雨" means "rain" in CHS. I think maybe this is a good method to translate it.

I'd appreciate that if you could reply to these questions, and, thanks for your excellent work, your mod brings a more exotic feeling to Minecraft, I feel so lucky that I have played this mod.

**Comment by noeppi-noeppi** [comment]
Yeah I'll take a look at these. However I'd suggest that you open a new issue next time as people normally don't look at closed issues.

**Comment by noeppi-noeppi** [comment]
Ok I'll reopen this now. Could you explain the changes you suggested for the raindeletia again? Google translate is very weird with it and I don't speak chinese. For point 2 I think this is ok as there's no endoblaze. For point 1 i am fine with you and I'll change this.

**Comment by DevilJueChen** [comment]
Rondeletia is the Chinese "郎德木" under your explanation, but in fact "郎德木" needs plenty of sunlight. I think it is more appropriate to translate as "时雨花". This follows your setting for raindeletia: "The raindeletia produces mana".
It depends on you.

**Comment by TUsama** [comment]
> Ok I'll reopen this now. Could you explain the changes you suggested for the raindeletia again? Google translate is very weird with it and I don't speak chinese. For point 2 I think this is ok as there's no endoblaze. For point 1 i am fine with you and I'll change this.

1. well, The "郎德木", which is the transliteration of "Rondeletia", doesn't mean anything in CHS. So I think maybe I could just change the "郎德" to "雨德". "雨" means "rain" in CHS. That is probably the best method to translate this "rond" "rain" trick. Also, maybe I can create a totally new word "时雨花", There is no such a flower in the real world, but literally it can show the function of this flower.
2. For point 2, ok, I just translate it to "溢焰花",  the "溢” means "overflow"(not very precise, but you can imagine it). But as you said that there is no "[exo-](https://www.etymonline.com/word/exo-#etymonline_v_14066)" meaning, so probably the "火焰花" is the precise translation. And maybe it could be “烈焰花", the difference between "火焰" and "烈焰" just like the "fire" and "blaze".

**Comment by DevilJueChen** [comment]
I also agree that Aquapathus is named Hundred Water Lotus["百水莲"]
Then:
1. Exoblaze is still "flaming flower".
2. Aquapanthus changed to "Hundred Water Lotus".
3. Raindeltia depends on your choice.
Author, after you decide, I will upload zh_cn.zip again.

**Comment by noeppi-noeppi** [comment]
Can you just choose which one matches best? I can not speak chinese and google translate does not help with those small details. Just choose which you think tells best what the flower does and if possible also includes the pun.

**Comment by TUsama** [comment]
that's the most difficult part lol, but we'll still try to figure it out!

**Comment by DevilJueChen** [comment]
Author, I have another question
Alfheim refers to Ljósálfar[ "Light Elf"], Still collectively referred to as "Elf"? If this is the case, how does Døkkálfar[ "Dark Elf"] explain it?

**Comment by noeppi-noeppi** [comment]
If you take a look at the runes of the nine world there's no rune for swartalfheim which is the world of the home of the dark elves. I choose nidavellir in that case (AFAIK we only have fragments of the norse mythology where it's not really clear what the nine world are and depending on where you look you'll find different answers) I chose to use nidavellir as the home of the dwarves over swartalfheim (which is often referred as the home of dark elves) to reduce ambiguity in this case as there are only light eleves in the content of mythic botany which are referred as just elves. Although I think dark elves are dwarves (im not sure though.) However in mythic botany there are only light elves and the other thing from nidavellir is a dwarf as I think this is more clear

**Comment by DevilJueChen** [comment]
So i need a specific answer
Does Alfheim refer to Elf.
Is swartalfheim just dwarves instead of Elf?

**Comment by noeppi-noeppi** [comment]
Yeah in mythicbotany Alfheim is the home of the elves and nidavellir is the home of the dwarves. There's no swartalfheim

**Comment by DevilJueChen** [comment]
thank you for your reply.
