### ISSUE TITLE
Extension suggestions

### ISSUE THREAD

**Issue by DevilJueChen** [noeppi-noeppi/MythicBotany#37]
If you want to expand the MOD in the future, then I make a suggestion: Ancient weapons in Norse mythology
1.（Gungnir）Is the main god in Norse mythology Odin weapon.This gun was made by the evil god Loki in the event of Insif’s Hair, and he asked the dwarf to make it，Gun point engraved Rune.
Effect:Can penetrate armor,Long-press and right-click to throw, [a period of time / hit the target / fall on the ground], and then return to the hand.

2.(Mulnir) Is a weapon that Loki got accidentally while teasing the gods and gnomes. It was later given to Thor to use. However, the grip of the weapon became slightly shorter because of Loki's mischief, so the dwarf who built it thought it was not perfect, but even so, Maulnir is still one of the strongest weapons in Norse mythology.
Effect:As a pendant.empty-handed Suffer damage,will appear in the hands,Taking itself as the radius, creatures within ten squares are struck by lightning,Then enter a 10 second cooldown.

I will list my two ideas first, if you think it is possible in the future, then I will take the time to design.

**Comment by noeppi-noeppi** [comment]
There'll be an update soon that add Mjöllnir (Your point 2). However I probably won't add Gungnir. The hammer however is different from what you suggested.

Thank you for the suggestions. I'll close this now. I hope you like how I implemented Mjöllnir

**Comment by DevilJueChen** [comment]
ohhh! This is great!
