### ISSUE TITLE
Cannot pick up Mjöllnir if placed down manually

### ISSUE THREAD

**Issue by Wxrlds** [noeppi-noeppi/MythicBotany#40]
Title says it all. This does only happen if you manually place it down with sneak + place. If your absorption effect runs out and you eat another golden apple you can pick it up just fine.

Mods used:
MythicBotany-1.16.4-1.3.2.jar
Minecraft: 1.16.5
Forge: 36.1.16
Botania-1.16.5-415.jar
curios-forge-1.16.5-4.0.5.1.jar
jei-1.16.5-7.6.4.87.jar
LibX-1.16.3-1.0.60.jar
Patchouli-1.16.4-50.jar

**Comment by KrAzYGEEK32** [comment]
so i have a similar issue, but my hammer vanished when i tried to pick it up, i was in a claimed chunk

**Comment by noeppi-noeppi** [comment]
Which version of MythicBotany?

**Comment by KrAzYGEEK32** [comment]
1.3.2

**Comment by noeppi-noeppi** [comment]
It was fixed in `1.3.3`. Please update.

**Comment by KrAzYGEEK32** [comment]
even if i update, i assume my hammer is gone for good?

**Comment by noeppi-noeppi** [comment]
Yes :(

**Comment by KrAzYGEEK32** [comment]
Oh well, RIP my short-lived hammer. Thanks for your time ☺️
