### ISSUE TITLE
Biome Conflicts

### ISSUE THREAD

**Issue by imskejutori** [noeppi-noeppi/MythicBotany#43]
My dimension has none of the mythic botany biomes, instead i have:
 the poise forest from The Endergetic Expansion
 the nemophila fields, lavender fields and forests from Abundance
 And rainforest biomes from Atmospheric,
Also the end biome in Alfheim has an abnormal amount of one of the end alex's mobs.
![image](https://user-images.githubusercontent.com/83618754/116945617-08ddcb80-ac70-11eb-8833-2d29311313d9.png)
![image](https://user-images.githubusercontent.com/83618754/116945644-1e52f580-ac70-11eb-9036-16df0eb21082.png)

**Comment by noeppi-noeppi** [comment]
Not reproducible for me. I tries adding MythicBotany afterwards or other dimension mods after MythicBotany but I always got a normal Alfheim. However I uploaded an alpha version on CurseForge where I think this could fix it. So could you please test it with that version and reply whether it fixed the issue.

https://www.curseforge.com/minecraft/mc-mods/mythicbotany/files/3297934
