### ISSUE TITLE
Andwari cave

### ISSUE THREAD

**Issue by aqpoyo** [noeppi-noeppi/MythicBotany#45]
Hi. I play on Enigmatica 6 mudpack and I have been trying to find an andwari cave for quite a while and can not find any. I try with in spectator looking under the golden fields biome and nothing. Could it be bug? Can you show us an example of the cave because in the book you don't see it very well. Is there a way to generate it? Thanks!

**Comment by DevilJueChen** [comment]
as the picture shows:

![image](https://user-images.githubusercontent.com/70829441/117039342-3e032000-ad3b-11eb-960c-385d57c77de4.png)
![image](https://user-images.githubusercontent.com/70829441/117039491-6ab73780-ad3b-11eb-8cc7-c9f353e15863.png)

**Comment by noeppi-noeppi** [comment]
You can locate a cave with `/locate mythicbotany:andwari_cave`. I'll tweak the structure spawn settings a bit.

**Comment by aqpoyo** [comment]
Ok thanks! found it at -3000 -6000... bit far jeje
