### ISSUE TITLE
Possible biome ID conflicts with Biomes o' Plenty

### ISSUE THREAD

**Issue by lk40games** [noeppi-noeppi/MythicBotany#46]
After installing the mod on a server (World gen mods being Biomes o' Plenty and Terraforged) All the existing biomes besides vanilla ones were changed to different biomes. Below are the before image (from a backup taken before adding the mod) and what the same area looked like after adding the mod. I have also added a screenshot of the world map showing the affected areas I had not reloaded 
![2021-05-06_14 23 13](https://user-images.githubusercontent.com/83783143/117349450-61cc8000-ae79-11eb-8450-7712277b59f4.png)
![2021-05-06_14 13 18](https://user-images.githubusercontent.com/83783143/117349464-65f89d80-ae79-11eb-8bad-ed3cacc911c3.png)
![2021-05-06_14 23 45](https://user-images.githubusercontent.com/83783143/117349512-74df5000-ae79-11eb-8710-ff30b81d7554.png)
In the images above the Highland biome was changed to a Fungal Jungle, and not all but many of the snowy biomes were changed to other types of snowy biomes.

**Comment by noeppi-noeppi** [comment]
Which version are you using?

**Comment by noeppi-noeppi** [comment]
Probably related to #43. Keep track of the issue there.
