### ISSUE TITLE
Crash when viewing Lexica entry for Mjolnir

### ISSUE THREAD

**Issue by LordGuppy** [noeppi-noeppi/MythicBotany#48]
To reproduce the bug, at least with my modlist: start up a new world, Use jei to give yourself a lexica botania, click through the the mjolnir entry, then page over a couple times and the game will hang then crash.

https://pastebin.com/MRvTzc4j

**Comment by noeppi-noeppi** [comment]
Which version of patchouli are you using?

**Comment by LordGuppy** [comment]
1.16.4-51
