### ISSUE TITLE
Game crashing when trying to select MJollnir, Alfiem, Alfiem Landscape, Mead of Kvasir, Resources of Alfiem and Ring of Andwari from Lexica Botania

### ISSUE THREAD

**Issue by JenniferWhite** [noeppi-noeppi/MythicBotany#51]
I'm reporting this for a friend of mine who plays on my server with my boyfriend and I that has this mod installed in it as well , everytime he tries to select something in the Lexica book that is from Mythical he crashes immediately after.

**Comment by noeppi-noeppi** [comment]
Duplicate of #48.

Update MythicBotany and Patchouli to the latest versions.
