### ISSUE TITLE
Alfheim portal not teleporting

### ISSUE THREAD

**Issue by missmaddles** [noeppi-noeppi/MythicBotany#52]
Me and a friend are having trouble with the portal. Yesterday when I tried to get back to the overworld (yes I had drank the mead), the screen would flash green but never take me back. Today a friend tried to go there (yes he drank the mead and the well water) and the same thing was happening where the screen would flash green but then never teleport. I was also having an issue where the alfheim dimension seemed to be taken over by the poise forest from Endergetic Expansion and some other biome mods (saw you already had an issue open for that, thought itd be helpful to know more people were having the issue ?).

**Comment by noeppi-noeppi** [comment]
Please see https://git.io/weirdmods

If you have any of these installed, please try without. If not, please send me your mod list

**Comment by noeppi-noeppi** [comment]
I'll close this now as there has been no reply for 17 days. If the issue persists, please leave another comment and I'll reopen the issue.
