### ISSUE TITLE
Mjolnir flying off with no end

### ISSUE THREAD

**Issue by Shroomicus** [noeppi-noeppi/MythicBotany#53]
In Valhelsia 3, V3.2.2, when throwing the hammer, sometimes when it hits a block or something of the like, it will just continue flying off and never return to your inventory.

**Comment by Shroomicus** [comment]
Update, it was just a weird interaction with Astral Soecery.

**Comment by daveshack-ibm** [comment]
@Shroomicus did it eventually come back, or gone forever?

**Comment by HammerDave** [comment]
@Shroomicus did it come back eventually or gone forever? Someone on my server seems to have also hit this.
