### ISSUE TITLE
Mjoellnir Config Hold Requirement

### ISSUE THREAD

**Issue by ToasterTricks** [noeppi-noeppi/MythicBotany#55]
I've tried using "none", "nothing", and "NOTHING" for the Mjoellnir Hold Requirement Config to match the enum but regardless, it always requires the absorption effect to be active to wield.

Config file:
`// What is required for a player to hold mjoellnir.
    // nothing - Players will always be able to hold mjoellnir.
    // effect  - Players need the absorption effect to hold mjoellnir.
    // hearts  - Players need absorption hearts to hold mjoellnir.
    //           If they run out of golden hearts but still have the effect, mjoellnir is dropped.
    // Allowed values: nothing, effect, hearts
    "requirement": "NOTHING",`
    
Expected behavior:
Setting "nothing" in the config allows a standard survival player with no effects active to wield Mjoellnir.

Actual behavior:
Mjoellnir requires the absorption effect to be active to wield.

**Comment by noeppi-noeppi** [comment]
Did you restart the game or reload the config with `/libx reload`?

**Comment by ToasterTricks** [comment]
Completely new single player world

**Comment by noeppi-noeppi** [comment]
Not reproducible for me. What happens if you run `/libx reload` even if it is a completely new world?

**Comment by noeppi-noeppi** [comment]
I'll close this now as there has been no reply for seven days. If the issue persists, please leave another comment and I'll reopen the issue.
