### ISSUE TITLE
Allow more items to be consumed in custom rune rituals

### ISSUE THREAD

**Issue by Wxrlds** [noeppi-noeppi/MythicBotany#57]
It would be nice if it were possible to make custom rune ritual recipes in which multiple items are consumed and not just the item on the master rune holder.
I can imagine that it could be implemented with a consume_item flag in the input so the recipe would look like that:
```json
{
  "type": "mythicbotany:rune_ritual",
  "group": "rune_rituals",
  "center": {
    "item": "mythicbotany:fimbultyr_tablet"
  },
  "runes": [
    {
      "rune": {
        "tag": "botania:runes/wrath",
        "consume_item": true <---
      },
      "x": -5,
      "z": 0
        },
        {
      "rune": {
        "tag": "botania:runes/earth",
        "consume_item": false <---
      },
      "x": -3,
      "z": -2
        }
  ],
  "mana": 500000,
  "ticks": 200,
  "inputs": [
    {
      "item": "minecraft:polished_andesite"
    }
  ],
  "outputs": [],
  "special_output": "mythicbotany:mjoellnir"
}
```
In this example the wrath rune would get consumed and the earth rune would not get consumed

**Comment by LeonardoTeixeira00** [comment]
Even with 'true' on 'consume flag' the ritual does not consume the rune.
![Recipe](https://user-images.githubusercontent.com/92516156/196773511-f8b61a4f-0905-40ae-80f1-afa75c11a9dc.PNG)

<recipetype:mythicbotany:rune_ritual>.addJsonRecipe("azure_silver_ingot",
{
  "type": "mythicbotany:rune_ritual",
  "group": "rune_rituals",
  "center": {
    "item": "botania:gaia_ingot"
  },
  "runes": [
    {
      "rune": {
        "item": "mythicbotany:alfheim_rune"
      },
      "x": 2,
      "z": 2,
      "consume": true
    },
    {
      "rune": {
        "item": "mythicbotany:midgard_rune"
      },
      "x": -2,
      "z": 2,
      "consume": true
    },
    {
      "rune": {
        "item": "botania:rune_envy"
      },
      "x": -2,
      "z": -2,
      "consume": true
    },
    {
      "rune": {
        "item": "botania:rune_mana"
      },
      "x": 2,
      "z": -2,
      "consume": true
    },
    {
      "rune": {
        "item": "botania:rune_air"
      },
      "x": 4,
      "z": 4,
      "consume": true
    },
    {
      "rune": {
        "item": "botania:rune_fire"
      },
      "x": -4,
      "z": -4,
      "consume": true
    },
    {
      "rune": {
        "item": "botania:rune_earth"
      },
      "x": -4,
      "z": 4,
      "consume": true
    },
    {
      "rune": {
        "item": "botania:rune_water"
      },
      "x": 4,
      "z": -4,
      "consume": true
    },
    {
      "rune": {
        "item": "mythicbotany:muspelheim_rune"
      },
      "x": -4,
      "z": 0,
      "consume": true
    },
    {
      "rune": {
        "item": "mythicbotany:niflheim_rune"
      },
      "x": 4,
      "z": 0,
      "consume": true
    }
  ],
  "mana": 0,
  "ticks": 200,
  "inputs": [
    {
      "item": "mekanism:dust_lapis_lazuli"
    },
    {
      "item": "mekanism:dust_lapis_lazuli"
    },
    {
      "item": "thermal:silver_ingot"
    },
    {
      "item": "minecraft:chorus_fruit"
    },
    {
      "item": "minecraft:chorus_fruit"
    },
    {
      "item": "minecraft:chorus_fruit"
    },
    {
      "item": "minecraft:chorus_fruit"
    }
  ],
  "outputs": [
    {
      "item": "moremekanismprocessing:azure_silver_ingot",
      "count": 1
    }
  ]
});

**Comment by noeppi-noeppi** [comment]
Please open a new issue then
