### ISSUE TITLE
Support for 1.16.4

### ISSUE THREAD

**Issue by Unhook** [noeppi-noeppi/MythicBotany#6]
Could you make it support 1.16.4 as well?

**Comment by noeppi-noeppi** [comment]
1.16.3 mods should in theory work with 1.16.4. I have not tested it though.

**Comment by Unhook** [comment]
Yes, but could you mark it as 1.16.4 as well? So it shows up on Twitch

**Comment by noeppi-noeppi** [comment]
I will when I tested it. But as this is a very boring task I'll probably do it next weekend

**Comment by noeppi-noeppi** [comment]
Done
