### ISSUE TITLE
Dispersive augments void mana using the greatest band of mana

### ISSUE THREAD

**Issue by JJSax** [noeppi-noeppi/MythicBotany#60]
When you are feeding the alf steel mana band with a dispersive spark augment, the ring never appreciates it's buffer.  I went from nearly level 300 XP to almost 0 and I didn't see any change beyond what I would expect from my terrasteel armor generation.  From my experience the farm I was using could fill about 2-3 terrasteel mana rings in that time, though that is an estimation.

Mod Version: 1.3.15
Forge Version: 36.1.18

**Comment by noeppi-noeppi** [comment]
Not reproducible. Are you sure its because of the greatest band of mana? have you tried to remove every other mana item (including the terrasteel armor) from your inventory?

**Comment by JJSax** [comment]
Good call.  It turns out it was my terra/alfshatterer.  I wasn't aware it would try to fill the terrashatterer.   Definitely not a bug.
