### ISSUE TITLE
Rune ritual better mana cost bar

### ISSUE THREAD

**Issue by Wxrlds** [noeppi-noeppi/MythicBotany#63]
It would be nice if the JEI page of rune rituals would show how many mana pools it needs for a recipe. So basically the same bar that's already in the mana infuser but for rune rituals
Essentially this bar
![grafik](https://user-images.githubusercontent.com/42120270/124355730-03224900-dc13-11eb-82f7-570cefe5cd61.png)
but on the JEI page for rune rituals:
![grafik](https://user-images.githubusercontent.com/42120270/124355857-9d828c80-dc13-11eb-9e26-f7c6d72bb6fd.png)

**Comment by noeppi-noeppi** [comment]
I want to stick with botania here which also does not have this. Rune rituals were never meant to consume that much maan that a regular bar is not enough to display it.

**Comment by Wxrlds** [comment]
Hmm, considering that https://github.com/noeppi-noeppi/MythicBotany/issues/65 limits the maximum mana cost to 4.000.000 mana how about making it so the bar looks like the bar from the mana infuser from before the update? So it says that it's a zoomed view?
![grafik](https://user-images.githubusercontent.com/63002502/120480548-74ba6d80-c3af-11eb-852a-d667244d1d6f.png)

**Comment by noeppi-noeppi** [comment]
You can also use these amounts of mana in for example the runic altar. And it also has no way to display them properly. If you're using them, you need to make that clear to the user in a different way.
