### ISSUE TITLE
Rune ritual only considers one band of mana

### ISSUE THREAD

**Issue by Wxrlds** [noeppi-noeppi/MythicBotany#65]
When you have a recipe that needs 1.000.000 mana, the recipe only works if you have a greater or greatest band of mana filled with more than 1.000.000 mana. This means you cannot have two normal bands of mana on you to perform the rune ritual. Each band of mana stores 500.000 mana so having two on you should provide enough mana but instead you need at least a greater band of mana for the recipe to work.
Using:
Minecraft 1.16.5
Forge 36.1.32
MythicBotany-1.16.4-1.3.15
Botania-1.16.5-418

**Comment by noeppi-noeppi** [comment]
This is a limitation of the botania API that it only considers one item for one request. I could request multiple times but with that I would not be able to simulate the request any more so it would not be possible to check for the ingredients before removing the mana from the inventory.
