### ISSUE TITLE
create ru.ru.json

### ISSUE THREAD

**Issue by konstantinshelskiy** [noeppi-noeppi/MythicBotany#68]
Hi, you need to expand the mod, namely to translate it into other languages. I just want to offer a translation of the mod into Russian, and if you like it, you can add it to the mod.

Here is my translation, please rate it:
https://drive.google.com/file/d/1SVTOojykUwpelfrLZYBZjKezvJp0mG7z/view

**Comment by noeppi-noeppi** [comment]
You should create a pull request for this: https://docs.github.com/en/github/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request
