### ISSUE TITLE
[1.3.15] Client crash when placing a runeholder at z=0

### ISSUE THREAD

**Issue by radiomike** [noeppi-noeppi/MythicBotany#69]
As above, divide by zero error on client when placing runeholder at z=0. Also crashes with same error when rejoining world. Haven't tested x=0 or y=0.

Crash report attached. 

[crash-2021-07-08_20.57.14-client.txt](https://github.com/noeppi-noeppi/MythicBotany/files/6787008/crash-2021-07-08_20.57.14-client.txt)

**Comment by radiomike** [comment]
Duplicate of #59

**Comment by noeppi-noeppi** [comment]
I kept this open intentionally to remind me to publish that version. It's now on CurseForge

**Comment by radiomike** [comment]
No problem, thanks for that.
