### ISSUE TITLE
Mana collector doesn't work

### ISSUE THREAD

**Issue by Nagispace** [noeppi-noeppi/MythicBotany#7]
I placed my mana collector near a terra-steel setup and tried to bind my flowers to it but it seems the mana doesn't go into the spark network at all.
![image](https://user-images.githubusercontent.com/65559593/98833553-7554dc00-243e-11eb-91b5-5a5955e36d78.png)

**Comment by MDeBuff** [comment]
Have you tried placing a spark and a recessive augment on it? That worked for me.

**Comment by noeppi-noeppi** [comment]
Yep the spark is missing. It's essentially a little mana storage that can directly be accessed by flowers and sparks.

**Comment by Nagispace** [comment]
I then suggest you to change the description as it suggest that it works without anything else.
Putting a spark alone won't work.
A schema would also be nice
![image](https://user-images.githubusercontent.com/65559593/98852299-c45b3b00-2457-11eb-917c-fdc171efe303.png)
