### ISSUE TITLE
Standing in the alfheim portal teleports you again and again

### ISSUE THREAD

**Issue by Wxrlds** [noeppi-noeppi/MythicBotany#71]
Essentially when you enter the alfheim portal, get teleported and continue standing in the portal, it teleports you into the overworld again, and back to alfheim,... instead of doing nothing after the first teleportation. My suggestion would be to either teleport the player not into the portal block but right next to it or do it like vanilla with their nether-portal delay so you have to get out of the portal before being able to change dimensions again

MythicBotany-1.16.4-1.3.18

**Comment by noeppi-noeppi** [comment]
This is intended. I think it feels more natural and you have plenty of time to leave the portal.
