### ISSUE TITLE
Aquapanthus and infinite potions

### ISSUE THREAD

**Issue by LunafeyLazuli** [noeppi-noeppi/MythicBotany#73]
So with MythicBotany and Inspirations both installed, if you put a potion or dye into the cauldron and bottle some of it, the Aquapanthus will fill it back up with the potion/dye basically letting you infinitely dupe potions and dyes. Is it possible to add a config to remove the Aquapanthus filling up cauldrons?

**Comment by noeppi-noeppi** [comment]
I think I'll just add a check when Inspirations is installed that the Aquapathus will only fill cauldrons with water inside.
