### ISSUE TITLE
Crash when launching game

### ISSUE THREAD

**Issue by lartts** [noeppi-noeppi/MythicBotany#75]
Forge Version:
- 36.2.2

Mod Version:
- 1.4.1

Crash Reports/Logs:
[2021-08-20-7.log](https://github.com/noeppi-noeppi/MythicBotany/files/7021893/2021-08-20-7.log)

**Comment by noeppi-noeppi** [comment]
Have you noticed, that the log you sent actually contains the word *MythicBotany* exactly 0 times? Why do you think, this is a MythicBiotany problem.
And if you think so, please see https://git.io/weirdmods , test without the mods listed there and create a new issue where you explain why you think, MythicBotany is responsible.

**Comment by lartts** [comment]
I uploaded the wrong log, but yeah MythicBotany wasn't the problem, Enhanced Celestials was. Sorry for bothering you!
