### ISSUE TITLE
Alf Shatterer not working w/Armor

### ISSUE THREAD

**Issue by MDeBuff** [noeppi-noeppi/MythicBotany#8]
I am using the current ATM 6 modpack (MythicBotany-1.16.3-1.1.3) and found that when I have full alfsteel armor equipped or greatest band of aura. I am unable to mine anything with the alf shatterer. I replicated it in a new world and had the same issue. 

Updated to MythicBotany 1.1.6 and had the same issue.

Looking through the code I'd say something to do with both the alfsteel helm, and the greatest band of aura not being in the Terra_pick_blacklist tag. 

(I've never done an issue report so if its rude to offer a suggestion on where too look my bad. I really love botania and this mod added a lot of what I felt I was missing. Great job!l

**Comment by noeppi-noeppi** [comment]
Actually It would have taken me quite some time to figure it out so your first issue report is pretty good. I wish everyone told me where exactly the problem is in the code.
