### ISSUE TITLE
Mythic Botany Mod causes Atum 2 Portal to not teleport the player

### ISSUE THREAD

**Issue by MrNoe93** [noeppi-noeppi/MythicBotany#80]
Adding an issue here as requested in the Atum 2 [issue](https://github.com/TeamMetallurgy/Atum2/issues/344).

Some interaction between the Atum 2 mod and the Mythic Botany Mod makes the Atum 2 portal not teleport the player. It forms just fine but doesnt do anything when the player steps in. Tried with just those two mods (and required dependencies) and still got the same result.

Forge: 36.2.0
Atum 2: 2.2.7
Mythic Botany: 1.4.9

**Comment by noeppi-noeppi** [comment]
Not reproducible for me. Try updating MythicBotany to 1.4.10 and all dependencies to their latest version, if that not helps, provide a log.

**Comment by MrNoe93** [comment]
Updating MythicBotany to 1.4.10 fixed the issue.  Thank you!
