### ISSUE TITLE
Suggestion 

### ISSUE THREAD

**Issue by RootUser-sys** [noeppi-noeppi/MythicBotany#86]
Add an additional item that will act as a stand for rings and an terra picker so that you can put an item on this stand and not be afraid that it will disappear, the stand will stand above the mana pool and take mana from there.
(example - https://www.curseforge.com/minecraft/mc-mods/botania-needs-these-things)

**Comment by noeppi-noeppi** [comment]
Maybe the mana battery from [botanical machinery](https://www.curseforge.com/minecraft/mc-mods/botanical-machinery) suits your needs.

**Comment by noeppi-noeppi** [comment]
Will not be added to MythicBotany, Use botanical machinery
