### ISSUE TITLE
Raindeletia's only function during Thunderstorms

### ISSUE THREAD

**Issue by Merithor** [noeppi-noeppi/MythicBotany#87]
Whats supposed to happen:
Curseforge page and Lexica entries say it works during the rain and is boosted during a Thunderstorm.

Whats happening now:
Only functions during a Thunderstorm. Or pages need updating.

MC: 1.16.5
Version: 1.4.14 (latest)

**Comment by noeppi-noeppi** [comment]
It only works during thunderstorms on regular soil. This is intended. Place it on vivid grass or enchanted soil to make it work during normal rain.
