### ISSUE TITLE
Alf shatterer won't mine blocks

### ISSUE THREAD

**Issue by Orbsolote** [noeppi-noeppi/MythicBotany#9]
Whenever I wear something from alfsteel upgrade (greatest ring of aura or alfsteel complete armor set) and it's supposed to regen my mana it won't let me fully mine any blocks. I think it's maybe stuck repairing it because in normal botany when the pickaxe is being repaired by the band of mana I had the same issue. Any suggestions?

**Comment by Nagispace** [comment]
Should be fixed in latest version.

**Comment by noeppi-noeppi** [comment]
Duplicate of #8
