### ISSUE TITLE
Faded nether star despawns

### ISSUE THREAD

**Issue by EuSuntMarian** [noeppi-noeppi/MythicBotany#90]
Mc Version: 1.16.5
Forge Version: 36.2.4
Mod Version: MythicBotany-1.16.5-1.4.19.jar

The Wither Aconite should make 2 mana pools. However, the faded nether star despawns before that can happen. Around half a mana pool, the item just disappears. Is that intended? I see you just have to set an `Age` NBT tag for the item entity with `-32768`.

**Comment by noeppi-noeppi** [comment]
That is intended. Either use a hopperhock and some other botania things to build a system to repeatedly drop the faded nether star or invest in a mana collector.

**Comment by EuSuntMarian** [comment]
Got it. Thanks a lot.

**Comment by EuSuntMarian** [comment]
Oh, but one more thing. Shouldn't this be stated in the Lexica Botania or something? I kinda lost a nether star with this thing :/
