### ISSUE TITLE
Clash With Vampirysm Biomes

### ISSUE THREAD

**Issue by GoldenMaster8** [noeppi-noeppi/MythicBotany#93]
I am running a forge 1.16.5 server with friends and the biome for the vampire forest seems to be replaced with the alfheim plains biome.

**Comment by Minecrafl** [comment]
这是来自QQ邮箱的假期自动回复邮件。你好，我最近正在休假中，无法亲自回复你的邮件。我将在假期结束后，尽快给你回复。

**Comment by noeppi-noeppi** [comment]
I think this might be related to #43. I'll close it here, in favour of #43

**Comment by Minecrafl** [comment]
这是来自QQ邮箱的假期自动回复邮件。你好，我最近正在休假中，无法亲自回复你的邮件。我将在假期结束后，尽快给你回复。
