### ISSUE TITLE
Issue: Wither Aconite does not work at range

### ISSUE THREAD

**Issue by TBrauns** [noeppi-noeppi/MythicBotany#95]
Botania's generating flowers allow things to be dropped nearby. For example, an Endoflame will consume a nearby flammable item for mana.

The Wither Aconite, at the very least, requires the Nether Star to be dropped into the same square. It does not work at the same range as Botania's generating flowers.

**Comment by noeppi-noeppi** [comment]
This is intended so you can't use multiple wither aconites that use up the same nether star as it would then be used up way faster.
