### ISSUE TITLE
Crash when Entering Alfheim

### ISSUE THREAD

**Issue by Cicopath** [noeppi-noeppi/MythicBotany#96]
I am playing a modded server with my brothers, and when I entered the portal to Alfheim, the server kept closing. I am unsure what is causing this. Here is the server log (the error begins at line 652): https://pastebin.com/mfSHbPQT

(Post has been edited to provide a pastebin.com link instead. I have no clue what the Chinese comment is.)

**Comment by Minecrafl** [comment]
这是来自QQ邮箱的假期自动回复邮件。你好，我最近正在休假中，无法亲自回复你的邮件。我将在假期结束后，尽快给你回复。

**Comment by Cicopath** [comment]
I forgot to provide specifics. This is on version 1.18.1 of MythicBotany. I fear it may be an incompatibility with biomes from Biomes O' Plenty, Oh The Biomes You'll Go, The Graveyard Biomes, and Blue Skies (a mod that adds two new dimensions),

**Comment by Cicopath** [comment]
After testing in a singleplayer world, there seems to be no problems. Is it a server RAM issue? If so, then that is problematic, as we cannot increase our server RAM manually. We may have to skip out on Alfheim if this is the case, which is unfortunate.

**Comment by Cicopath** [comment]
When you say to restart the server, do you mean to start it again after the crash while I am still in the portal? If so, yes, and the crash still occurs. I had my brother break the Alfheim portal to prevent me from teleporting and crashing the server.
