### ISSUE TITLE
1.18.2 Request

### ISSUE THREAD

**Issue by CDAGaming** [noeppi-noeppi/MythicBotany#98]
As the title says, just wondering if a release could be pushed or tagged?

**Comment by noeppi-noeppi** [comment]
https://www.curseforge.com/minecraft/mc-mods/mythicbotany/files/3745023

**Comment by Minecrafl** [comment]
这是来自QQ邮箱的假期自动回复邮件。你好，我最近正在休假中，无法亲自回复你的邮件。我将在假期结束后，尽快给你回复。
